# golangci-lint configuration used for CI
run:
  tests: true
  timeout: 10m
  skip-dirs:
    - webhook
  skip-dirs-use-default: true

linters-settings:
  goimports:
    local-prefixes: github.com/vmware/load-balancer-and-ingress-services-for-kubernetes

linters:
  disable-all: true
  enable:
    - misspell
    - gofmt
    - deadcode
    - staticcheck
    - goimports
    - vet
