# This is a basic workflow to help you get started with Actions

name: Go-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  golangci-lint:
    name: Golangci-lint
    strategy:
      matrix:
        platform: [ ubuntu-18.04 ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Check-out code
      uses: actions/checkout@v2
    - name: Run golangci-lint
      run: make golangci